In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [26]:
df = pd.read_csv("./data/ECG/ECG200_TRAIN.txt", header=None, sep='\s+')

In [27]:
df.head()

0         1         2         3         4         5         6         7   \
0 -1.0  0.502055  0.542163  0.722383  1.428885  2.136516  2.281149  1.936274   
1  1.0  0.147647  0.804668  0.367771  0.243894  0.026614 -0.274402  0.096731   
2 -1.0  0.316646  0.243199  0.370471  1.063738  1.678187  1.759558  1.697717   
3 -1.0  1.168874  2.075901  1.760140  1.606446  1.949046  1.302842  0.459332   
4  1.0  0.648658  0.752026  2.636231  3.455716  2.118157  0.520620 -0.188627   

         8         9   ...        87        88        89        90        91  \
0  1.468890  1.008845  ...  0.931043  0.610298  0.638894  0.684679  0.583238   
1 -0.747731 -1.609777  ... -0.533503 -0.400228  0.176084  1.111768  2.438428   
2  1.612159  1.168188  ...  0.764229  0.610621  0.552900  0.566786  0.604002   
3  0.516412  0.852180  ...  0.419006  0.723888  1.323947  2.136488  1.746597   
4  0.780818  0.933775  ... -0.097869 -0.136787 -0.340237 -0.089441 -0.080297   

         92        93        94        95        96  
0  0.640522  0.708585  0.705011  0.713815  0.433765  
1  2.734889  1.736054  0.036857 -1.265074 -0.208024  
2  0.777068  0.812345  0.748848  0.818042  0.539347  
3  1.470220  1.893512  1.256949  0.800407  0.731540  
4 -0.192584 -0.304704 -0.454556  0.314590  0.582190  

[5 rows x 97 columns]

In [28]:
nrows, ncols = df.shape

In [29]:
w0 = np.zeros(ncols)

In [30]:
def sigmoid(z):
    return 1./(1+np.exp(-z))

def loss(w, x, y):
    p = predict(w,x)
    return -y*np.log(p)-(1-y)*np.log(1-p)

def grad(w,x,y):
    p = predict(w,x)
    return (p-y)*x

def predict(w,x):
    return sigmoid(np.dot(w,x))

# Online gradient descent

In [31]:
w = w0.reshape(1,-1)
eta = 1
for row in range(nrows):
    y = df.iloc[row, 0]
    x = df.iloc[row,:].values 
    x[0] = 1 # adding bias term
    
    # Update weights and step size
    w = w - eta*grad(w,x,y)
    eta = 1/np.sqrt(row+1)

In [32]:
predict(w,x)

array([1.])

In [33]:
df.iloc[-1,0]

1.0

# A larger dataset - Airbnb housing in Berlin

In [34]:
data = []
with open('./data/airbnb-berlin.csv', 'r', encoding='utf-8') as f:
    for line in f:
        data.append(line)
        if len(data)>5:
            break

In [35]:
data

[',date,available,longitude,latitude,minimum_nights,neighbourhood,number_of_reviews,room_type,price,apt_id\n',
 '0,2019-09-10,f,13.402556926822387,52.53453732241747,4,Brunnenstr. Süd,118,Entire home/apt,60,2015\n',
 '1,2019-09-09,f,13.402556926822387,52.53453732241747,4,Brunnenstr. Süd,118,Entire home/apt,60,2015\n',
 '2,2019-09-08,f,13.402556926822387,52.53453732241747,4,Brunnenstr. Süd,118,Entire home/apt,60,2015\n',
 '3,2019-09-07,f,13.402556926822387,52.53453732241747,4,Brunnenstr. Süd,118,Entire home/apt,60,2015\n',
 '4,2019-09-06,f,13.402556926822387,52.53453732241747,4,Brunnenstr. Süd,118,Entire home/apt,60,2015\n']

In [36]:
D = 50 # memory buffer

In [40]:
idx = abs(hash('pablo')) % 20

In [41]:
x = np.zeros(D)

In [42]:
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
x[idx] = 1

In [44]:
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])